### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by vlerenc**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```improvement operator

```

### CODE REVIEW

**Comment by gardener-botmanager** [comment]
@vlerenc Command /request-for-review is not known.

**Comment by gardener-botmanager** [comment]
@vlerenc Here my list of commands:
<details>
<summary>Man Page</summary>

| Synopsis | What&nbsp;&&nbsp;Who | Description&nbsp;&&nbsp;Examples |
|:----|:----|:----|
|`/assign`&nbsp;`[@user...]`|<sub>Valid for</sub><br/>Issue,<br/>PullRequest<br/><sub>Permitted for</sub><br/>Maintainer,<br/>Commenter|Assign given people (or yourself if none specified) to issue or PR. Commenters may only assign themselves.<br/><sub>Examples:</sub><br/>- `/assign`<br/>- `/assign @johndoe @janedoe`|
|`/unassign`&nbsp;`[@user...]`|<sub>Valid for</sub><br/>Issue,<br/>PullRequest<br/><sub>Permitted for</sub><br/>Maintainer,<br/>Commenter|Unassign given people (or yourself if none specified) from issue or PR. Commenters may only unassign themselves.<br/><sub>Examples:</sub><br/>- `/unassign`<br/>- `/unassign @johndoe @janedoe`|
|`/cla`|<sub>Valid for</sub><br/>PullRequest<br/><sub>Permitted for</sub><br/>Anyone|Recheck [Contributor License Agreement (CLA)](https://cla-assistant.io) for PR.<br/><sub>Examples:</sub><br/>- `/cla`|
|`/help`|<sub>Valid for</sub><br/>Issue,<br/>PullRequest<br/><sub>Permitted for</sub><br/>Anyone|Get help on all available commands.<br/><sub>Examples:</sub><br/>- `/help`<br/><sub>Synonyms: `/help`, `/hi`, `/hello`, `/hola`, `/hallo`, `/rtfm`</sub>|
|`/add`&nbsp;`label...`|<sub>Valid for</sub><br/>Issue,<br/>PullRequest<br/><sub>Permitted for</sub><br/>Maintainer,<br/>Author|Add label to issue or PR (default if no command is recognized). Authors may only add certain white-listed labels such as `kind/*`, `priority/*`, `area/*`, `component/*`, `platform/*`. The labels can be either fully qualified like `kind/bug`, just the identifier like `bug`, or starting with the category like `kind` followed by one or many identifiers in that category.<br/><sub>Examples:</sub><br/>- `/add area/cost component/gardener`<br/>- `/add cost gardener`<br/>- `/add kind bug regression`<br/>- `/area/cost component/gardener`<br/>- `/cost gardener`<br/>- `/kind bug regression`<br/><sub>Synonyms: `/add`, `/set`, `/label`, `/start`, `/begin`</sub>|
|`/remove`&nbsp;`label...`|<sub>Valid for</sub><br/>Issue,<br/>PullRequest<br/><sub>Permitted for</sub><br/>Maintainer|Remove label from issue or PR.<br/><sub>Examples:</sub><br/>- `/remove area/cost component/gardener`<br/>- `/remove cost gardener`<br/>- `/remove kind bug regression`<br/><sub>Synonyms: `/remove`, `/rem`, `/unset`, `/unlabel`, `/stop`, `/end`, `/del`, `/drop`, `/cancel`</sub>|
|`/lgtm`|<sub>Valid for</sub><br/>Issue,<br/>PullRequest<br/><sub>Permitted for</sub><br/>Maintainer|Add `reviewed/lgtm` label to issue or PR (and remove conflicting labels such as `reviewed/do-not-merge`).<br/><sub>Examples:</sub><br/>- `/lgtm`|
|`/hold`|<sub>Valid for</sub><br/>Issue,<br/>PullRequest<br/><sub>Permitted for</sub><br/>Maintainer|Add `reviewed/do-not-merge` label to issue or PR (and remove conflicting labels such as `reviewed/lgtm`).<br/><sub>Examples:</sub><br/>- `/hold`|
|`/unhold`|<sub>Valid for</sub><br/>Issue,<br/>PullRequest<br/><sub>Permitted for</sub><br/>Maintainer|Removes `reviewed/do-not-merge` label from issue or PR.<br/><sub>Examples:</sub><br/>- `/unhold`|
|`/close`|<sub>Valid for</sub><br/>Issue,<br/>PullRequest<br/><sub>Permitted for</sub><br/>Maintainer,<br/>Author|Close issue or PR.<br/><sub>Examples:</sub><br/>- `/close`|
|`/reopen`|<sub>Valid for</sub><br/>Issue,<br/>PullRequest<br/><sub>Permitted for</sub><br/>Maintainer,<br/>Author|Reopen issue or PR.<br/><sub>Examples:</sub><br/>- `/reopen`|
|`/touch`|<sub>Valid for</sub><br/>Issue,<br/>PullRequest<br/><sub>Permitted for</sub><br/>Maintainer,<br/>Author|Remove `lifecycle/icebox`, `stale`, or `rotten` label from issue or PR. Authors may only remove the `stale` or `rotten` labels.<br/><sub>Examples:</sub><br/>- `/touch`|
|`/plan`&nbsp;`milestone`|<sub>Valid for</sub><br/>Issue<br/><sub>Permitted for</sub><br/>Maintainer|Set milestone for issue.<br/><sub>Examples:</sub><br/>- `/plan 2030-Q1`<br/><sub>Synonyms: `/plan`, `/schedule`, `/milestone`</sub>|
|`/unplan`|<sub>Valid for</sub><br/>Issue<br/><sub>Permitted for</sub><br/>Maintainer|Unset milestone for issue.<br/><sub>Examples:</sub><br/>- `/unplan`<br/><sub>Synonyms: `/unplan`, `/unschedule`, `/unmilestone`</sub>|
|`/ping`&nbsp;`[@user...]`|<sub>Valid for</sub><br/>Issue,<br/>PullRequest<br/><sub>Permitted for</sub><br/>Anyone|Ping user to take a look at issue or PR.<br/><sub>Examples:</sub><br/>- `/ping @johndoe @janedoe`<br/><sub>Synonyms: `/ping`, `/notify`, `/look`, `/cc`</sub>|
|`/invite`&nbsp;`[@user...]`|<sub>Valid for</sub><br/>PullRequest<br/><sub>Permitted for</sub><br/>Maintainer,<br/>Author,<br/>Commenter|Request PR review from given people (or yourself if none specified) for PR. Commenters may only add themselves.<br/><sub>Examples:</sub><br/>- `/invite`<br/>- `/invite @johndoe @janedoe`<br/><sub>Synonyms: `/invite`, `/review`</sub>|
|`/ready-for-review`|<sub>Valid for</sub><br/>PullRequest<br/><sub>Permitted for</sub><br/>Maintainer,<br/>Author|Turn draft PR into ready for review PR.<br/><sub>Examples:</sub><br/>- `/ready-for-review`|
|`/uninvite`&nbsp;`[@user...]`|<sub>Valid for</sub><br/>PullRequest<br/><sub>Permitted for</sub><br/>Maintainer,<br/>Commenter|No longer request PR review from given people (or yourself if none specified) for PR. Commenters may only remove themselves.<br/><sub>Examples:</sub><br/>- `/uninvite`<br/>- `/uninvite @johndoe @janedoe`<br/><sub>Synonyms: `/uninvite`, `/unreview`</sub>|
|`/title`&nbsp;`title`|<sub>Valid for</sub><br/>Issue,<br/>PullRequest<br/><sub>Permitted for</sub><br/>Maintainer,<br/>Author|Change title of issue or PR.<br/><sub>Examples:</sub><br/>- `/title Add metrics endpoint`<br/><sub>Synonyms: `/title`, `/retitle`</sub>|
</details>

**Comment by vlerenc** [comment]
ready-for-review

**Comment by gardener-botmanager** [comment]
@vlerenc Command /convert-to-draft not implemented yet. GitHub doesn't offer a callable mutation (see https://developer.github.com/v4/mutation) and has exposed this functionality only in the UI so far.

**Pull request closed without merging**
